"""
Domain Models — Typed Data Contracts (V4 Upgrade)
===================================================
Pydantic models for all core domain objects in the pipeline.
These enforce type safety across all wheels, preventing silent
data corruption that can cost real money in production.

Every wheel MUST use these models instead of raw dicts/tuples.
"""
from pydantic import BaseModel, Field, field_validator
from typing import Optional, Literal
from datetime import datetime, date
from enum import Enum


# ========== ENUMS ==========

class SignalType(str, Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    HEDGE = "HEDGE"

class OrderStatus(str, Enum):
    QUEUED = "QUEUED"
    EXECUTING = "EXECUTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"

class MarketRegime(str, Enum):
    BULL = "Bull"
    BEAR = "Bear"
    SIDEWAYS = "Sideways"
    HIGH_VOL = "HighVol"

class StrategyCategory(str, Enum):
    QUANTITATIVE_FACTOR = "QuantitativeFactor"
    VOLATILITY = "Volatility"
    MICROSTRUCTURE = "Microstructure"

class ExitReason(str, Enum):
    HARD_STOP = "hard_stop"
    RL_EXIT = "rl_exit"
    ATR_TRAIL = "atr_trail"
    PROFIT_TARGET = "profit_target"
    STRATEGY_EXIT = "strategy_exit"
    TIME_DECAY = "time_decay"
    MANUAL = "manual"


# ========== MARKET DATA ==========

class MarketEvent(BaseModel):
    """Represents a single market data snapshot for a ticker."""
    ticker: str
    price: float = Field(gt=0, description="Current price, must be positive")
    open: float = Field(gt=0)
    high: float = Field(gt=0)
    low: float = Field(gt=0)
    close: float = Field(gt=0)
    volume: int = Field(ge=0)
    sector: str = ""
    timestamp: datetime = Field(default_factory=datetime.now)

    # Technical/Microstructure Indicators (optional, populated by Wheel 1)
    vwap: Optional[float] = None
    hurst: Optional[float] = None
    garch_vol: Optional[float] = None
    vpin: Optional[float] = None
    obi: Optional[float] = None
    micro_price: Optional[float] = None
    dealer_gex: Optional[float] = None
    insider_score: Optional[float] = None


# ========== SIGNALS ==========

class AlphaSignal(BaseModel):
    """A trading signal generated by Wheel 2 (Strategy Library)."""
    ticker: str
    signal_type: SignalType
    confidence: float = Field(ge=0.0, le=1.0, description="Signal confidence 0-100%")
    target_strategy: str
    supporting_strategies: list[str] = Field(default_factory=list)
    exit_rule: str = ""
    timestamp: datetime = Field(default_factory=datetime.now)

    @field_validator('confidence')
    @classmethod
    def confidence_must_be_valid(cls, v):
        if v < 0.0 or v > 1.0:
            raise ValueError(f'Confidence must be between 0.0 and 1.0, got {v}')
        return v


# ========== ORDERS ==========

class Order(BaseModel):
    """An order queued for execution by Wheel 3 (Risk Engine)."""
    ticker: str
    action: SignalType
    qty: float = Field(gt=0)
    estimated_price: float = Field(gt=0)
    strategy: str
    confidence: float = Field(ge=0.0, le=1.0)
    kelly_pct: float = Field(ge=0.0, le=1.0)
    status: OrderStatus = OrderStatus.QUEUED
    timestamp: datetime = Field(default_factory=datetime.now)


class Execution(BaseModel):
    """A filled execution returned from Alpaca."""
    ticker: str
    action: str
    qty: float
    fill_price: float
    alpaca_order_id: str
    timestamp: datetime = Field(default_factory=datetime.now)


class Fill(BaseModel):
    """Represents a partial or full fill of an order."""
    order_id: str
    ticker: str
    filled_qty: float
    fill_price: float
    commission: float = 0.0
    slippage: float = 0.0
    timestamp: datetime = Field(default_factory=datetime.now)


# ========== POSITIONS ==========

class Position(BaseModel):
    """A live portfolio position with full lifecycle tracking."""
    ticker: str
    qty: float
    entry_price: float = Field(gt=0)
    current_price: float = Field(gt=0)
    entry_date: date
    strategy: str
    sector: str = ""
    atr_at_entry: float = 0.0
    trailing_stop: Optional[float] = None
    unrealized_pnl: float = 0.0
    unrealized_pnl_pct: float = 0.0
    weight: float = 0.0  # Portfolio weight (0.0 - 1.0)

    @property
    def market_value(self) -> float:
        return self.qty * self.current_price

    @property
    def holding_days(self) -> int:
        return (date.today() - self.entry_date).days


# ========== RISK ==========

class RiskDecision(BaseModel):
    """
    The centralized risk authority's verdict on an order.
    NOTHING executes without a RiskDecision.approved == True.
    """
    approved: bool
    order: Order
    reason: str = ""
    adjusted_qty: Optional[float] = None
    adjusted_kelly: Optional[float] = None
    var_impact: Optional[float] = None
    correlation_check_passed: bool = True
    circuit_breaker_clear: bool = True
    sector_limit_clear: bool = True
    position_limit_clear: bool = True
    timestamp: datetime = Field(default_factory=datetime.now)


class PortfolioRisk(BaseModel):
    """Real-time portfolio risk snapshot."""
    total_value: float
    cash: float
    positions_count: int
    var_95: float = 0.0
    sharpe_ratio: float = 0.0
    sortino_ratio: float = 0.0
    max_drawdown: float = 0.0
    net_exposure: float = 0.0
    gross_exposure: float = 0.0
    beta: float = 0.0
    factor_exposures: dict[str, float] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=datetime.now)


class CircuitBreakerState(BaseModel):
    """Circuit breaker status."""
    is_halted: bool = False
    halt_reason: str = ""
    daily_pnl: float = 0.0
    daily_pnl_pct: float = 0.0
    trades_today: int = 0
    day_open_value: float = 0.0


# ========== STRATEGY ==========

class StrategyResult(BaseModel):
    """Output from a single strategy evaluation."""
    strategy_name: str
    signal: SignalType
    confidence: float = Field(ge=0.0, le=1.0)
    exit_rule: str = ""
    metadata: dict = Field(default_factory=dict)


class StrategyMetrics(BaseModel):
    """Performance metrics for a single strategy."""
    strategy: str
    win_rate: float = 0.0
    sharpe_ratio: float = 0.0
    avg_win: float = 0.0
    avg_loss: float = 0.0
    profit_factor: float = 0.0
    max_drawdown: float = 0.0
    total_trades: int = 0
    weight: float = 0.0


# ========== AI / ML ==========

class AIPrediction(BaseModel):
    """AI Strategy Selector prediction for a ticker."""
    ticker: str
    predicted_category: StrategyCategory
    confidence: float = Field(ge=0.0, le=1.0)
    recommended_strategy: str = ""
    regime: MarketRegime = MarketRegime.BULL
    regime_probabilities: dict[str, float] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=datetime.now)


class RLExitDecision(BaseModel):
    """Deep Q-Network exit decision for a position."""
    ticker: str
    action: Literal["HOLD", "SELL"]
    q_values: list[float] = Field(default_factory=list)
    state: list[float] = Field(default_factory=list)
    confidence: float = 0.0
    timestamp: datetime = Field(default_factory=datetime.now)


# ========== PAIRS TRADING ==========

class PairSignal(BaseModel):
    """Statistical arbitrage pair signal."""
    ticker_a: str
    ticker_b: str
    z_score: float
    half_life: float
    signal: SignalType
    spread: float = 0.0
    hedge_ratio: float = 1.0
    timestamp: datetime = Field(default_factory=datetime.now)

